### ISSUE TITLE
Reverted fixs

### ISSUE THREAD

**Issue by Galixte** [phpbbmodders/ban-hammer#16]
Hi @rmcgirr83,

- you have reverted my fixs from this PR: https://github.com/phpbbmodders/ban-hammer/pull/12, like this commit: https://github.com/phpbbmodders/ban-hammer/commit/9d14f5dab01a9fb01cc2db2b59c2fc03a3ff34b0#diff-ec5819cb3f77f22800325dd9a2fb5c02R59.

   - two language keys are similars:
   -in this extension:
  https://github.com/phpbbmodders/ban-hammer/blob/master/language/en/info_acp_banhammer.php#L59
   -and in that:
  https://github.com/rmcgirr83/phpBB-3.1-stopforumspam/blob/master/language/en/acp/acp_stopforumspam.php#L51

- And you have reverted the ```:``` instead of ```{L_COLON}```, like this commit: https://github.com/phpbbmodders/ban-hammer/commit/9d14f5dab01a9fb01cc2db2b59c2fc03a3ff34b0#diff-5b4f4e93758873602a5f9702d9ae4653R12.

Why ?

**Comment by rmcgirr83** [comment]
This is the exact reason as to why I don't pull in language files into my repos.  It is a gigantic pain in the ass especially if you don't speak the language and you are trying to update the extension.

That's why.

Stop forum spam doesn't even use that lang string so that's a non-issue and that lang file is only called when accessing the stop forum spam extension settings.

I will fix the colons.

**Comment by Galixte** [comment]
Thanks.
